### ISSUE TITLE
File change not detected 

### ISSUE THREAD

**Issue by ksamuel** [breuleux/jurigged#1]
I have the following snippet:

```python
import time

import jurigged


def experiment(*args, **kwargs):
    def decorator(func):

        while True:
            time.sleep(0.1)
            res = func(*args, **kwargs)
            print(repr(res), end="\r")

    return decorator


if __name__ == "__main__":

    @experiment()
    def main():
        a = 2
        return 1
```

If I run:

```bash
jurigged -v essai.py 
Watch /tmp/essai.py
```

I do get "1", but if I modify the code, jurigged doesn't "Update __main__.main" as usual. I suppose the decorator does something to it.

**Comment by breuleux** [comment]
There are basically two issues:

1. Jurigged does not inspect if statements, so it does not detect changes inside `if __name__ ...`. I don't really plan to support that for now because it could get wonky if e.g. both branches define a function with the same name.
2. The `experiment` decorator does not actually return, so the global variable `main` is never set, so even if you pulled it out of the `if` so that Jurigged could see the change, it wouldn't know what to update (it won't tell you about the problem, though, so that might be something to improve).

It will work if you do it like this:

```python
def main():
    a = 2
    return 1

if __name__ == "__main__":
    experiment()(main)
```

**Comment by ksamuel** [comment]
Thank you.
