### ISSUE TITLE
Support for pre- and post-update hooks

### ISSUE THREAD

**Issue by zevaryx** [breuleux/jurigged#18]
Essentially, I was hoping that it were possible to add support for custom hooks to run before and after updating the code in memory so that you can run pre- and post-update tasks. 

This is a fairly niche use case, but a Discord bot framework I'm working on (https://github.com/NAFTeam/NAFF) is looking to implement jurigged for fast-paced development of Discord bots, and re-registering command with Discord whenever files are changed. However, it's not really feasible, as doing so requires tracking everything both before and after the change, which currently isn't possible (that I'm aware of)

**Comment by breuleux** [comment]
Cool project! Some hooks could be useful, I agree.

On a per-file granularity, they could happen before and after https://github.com/breuleux/jurigged/blob/master/jurigged/live.py#L101 (on the object returned by `jurigged.watch`), which isn't too difficult to patch, if you need to. The existing module object should be in `cf.module` and old source code in `cf.root.codestring` (I really need to document all of this at some point).

Feel free to make a PR for this if you want to, otherwise I'll think about it when I get the bandwidth :)

**Comment by zevaryx** [comment]
Here's it being integrated into NAFF:
https://github.com/NAFTeam/NAFF/blob/jurigged/naff/ext/debug_extension/debug_jurigged.py

I'll go ahead and close this now
