### ISSUE TITLE
Working great on Ubuntu, but not on Windows

### ISSUE THREAD

**Issue by schollz** [breuleux/jurigged#9]
First of all - I *love* this code. Thank you so much for creating it. I'm using it to create a live-coding environment to make music with SuperCollider.

I had no problems running jurigged on Ubuntu, but I can't get it to work on Windows. I tried running it the same way: `python3 -m jurigged -v livecoding.py` but on Windows it never registers any change in the file when I save. I'm using Sublime on Windows to save. My python version is 3.9.7 and Windows version is 10. Is there a known issue with Windows?

**Comment by schollz** [comment]
Like it! I *love* it! Such a great piece of code.

It's happening with every editor I've tried - Sublime, Vim (in Powershell) and plain old Notepad.exe. Actually I don't think its an editor thing - I used Sublime + Ubuntu no problem. I worry that it might be a Windows thing, I saw that watchdog supports Windows though so I didn't think that was it. I did try updating all the dependencies to the latest version, but still has an issue. 

I can try doing the polling - could you point me to the code where it should be integrated? No problem if you are busy! I can poke around.

**Comment by breuleux** [comment]
I looked into it, I'm pretty sure the problem is that when watching a file, if the file is deleted and then recreated (which happens with the way some editors save), the watcher emits the deletion event and then *stops*. So I think it's sufficient to observe the file's parent directory instead of the file itself (basically a more fine-grained version of your fix).

I tested with editing the file through `vi` (which used to not work) and it seems to work, so that's good.

I also added a `--poll <INTERVAL>` option, in case that sometimes helps.

I pushed a new version, 0.3.5, with these fixes. Tell me if that does the trick!
